allowBuilds:
  esbuild: true
  simple-git-hooks: true
# allowBuilds:
#   '@parcel/watcher': true
#   core-js: true
#   esbuild: true
#   sharp: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
