catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.2
  vitest: 4.1.9
  vite-plus: 0.2.2
  '@vitest/browser-playwright': 4.1.9
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'

allowBuilds:
  esbuild: true
  simple-git-hooks: true
