export default [{
    path: 'api/player/jumpTo',
    method: 'POST',
    name: 'actions.player.jumpTo',
    dispatch: true
}, {
    path: 'api/player/next',
    method: 'GET',
    name: 'actions.player.next',
    dispatch: true
}, {
    path: 'api/player/pause',
    method: 'GET',
    name: 'actions.player.pause',
    dispatch: true
}, {
    path: 'api/player/play',
    method: 'GET',
    name: 'actions.player.play',
    dispatch: true
}, {
    path: 'api/player/playToggle',
    method: 'GET',
    name: 'actions.player.playToggle',
    dispatch: true
}, {
    path: 'api/player/previous',
    method: 'GET',
    name: 'actions.player.previous',
    dispatch: true
}, {
    path: 'api/player/repeat',
    method: 'GET',
    name: 'actions.player.repeat',
    dispatch: true
}, {
    path: 'api/player/setMuted',
    method: 'POST',
    name: 'actions.player.setMuted',
    dispatch: true
}, {
    path: 'api/player/setPlaybackRate',
    method: 'POST',
    name: 'actions.player.setPlaybackRate',
    dispatch: true
}, {
    path: 'api/player/setVolume',
    method: 'POST',
    name: 'actions.player.setVolume',
    dispatch: true
}, {
    path: 'api/player/shuffle',
    method: 'GET',
    name: 'actions.player.shuffle',
    dispatch: true
}, {
    path: 'api/player/start',
    method: 'POST',
    name: 'actions.player.start',
    dispatch: true
}, {
    path: 'api/player/stop',
    method: 'GET',
    name: 'actions.player.stop',
    dispatch: true
}];
