export default [{
    path: 'api/actions/player/jumpTo',
    method: 'POST',
    name: 'actions.player.jumpTo',
    dispatch: true
}, {
    path: 'api/actions/player/next',
    method: 'POST',
    name: 'actions.player.next',
    dispatch: true
}, {
    path: 'api/actions/player/pause',
    method: 'GET',
    name: 'actions.player.pause',
    dispatch: true
}, {
    path: 'api/actions/player/play',
    method: 'GET',
    name: 'actions.player.play',
    dispatch: true
}, {
    path: 'api/actions/player/playToggle',
    method: 'GET',
    name: 'actions.player.playToggle',
    dispatch: true
}, {
    path: 'api/actions/player/previous',
    method: 'POST',
    name: 'actions.player.previous',
    dispatch: true
}, {
    path: 'api/actions/player/repeat',
    method: 'GET',
    name: 'actions.player.repeat',
    dispatch: true
}, {
    path: 'api/actions/player/setMuted',
    method: 'POST',
    name: 'actions.player.setMuted',
    dispatch: true
}, {
    path: 'api/actions/player/setPlaybackRate',
    method: 'POST',
    name: 'actions.player.setPlaybackRate',
    dispatch: true
}, {
    path: 'api/actions/player/setVolume',
    method: 'POST',
    name: 'actions.player.setVolume',
    dispatch: true
}, {
    path: 'api/actions/player/shuffle',
    method: 'GET',
    name: 'actions.player.shuffle',
    dispatch: true
}, {
    path: 'api/actions/player/loadAndPlay',
    method: 'POST',
    name: 'actions.player.loadAndPlay',
    dispatch: true
}, {
    path: 'api/actions/player/load',
    method: 'POST',
    name: 'actions.player.load',
    dispatch: true
}, {
    path: 'api/actions/player/stop',
    method: 'GET',
    name: 'actions.player.stop',
    dispatch: true
}, {
    path: 'api/actions/player/createNewQueue',
    method: 'POST',
    name: 'actions.player.createNewQueue',
    dispatch: true
}];
