module.exports.IPCR_APP_RESTART = 'IPCR_APP_RESTART';
module.exports.IPCR_APP_CLOSE = 'IPCR_APP_CLOSE';

module.exports.IPCR_PLAYER_ACTION = 'IPCR_PLAYER_ACTION';
module.exports.IPCM_TL_CONTEXTMENU_REPLY = 'IPCM_TL_CONTEXTMENU_REPLY';

module.exports.IPCM_PL_CONTEXTMENU_REPLY = 'IPCM_PL_CONTEXTMENU_REPLY';
module.exports.IPCR_TOGGLE_SLEEPBLOCKER = 'IPCR_TOGGLE_SLEEPBLOCKER';
