enum ActionTypes {
  LIBRARY_REFRESH = 'LIBRARY_REFRESH',
  REFRESH_CONFIG = 'REFRESH_CONFIG',

  FILTER_SEARCH = 'FILTER_SEARCH',

  LIBRARY_SORT = 'LIBRARY_SORT',
  LIBRARY_RESET = 'LIBRARY_RESET',
  LIBRARY_REFRESH_START = 'LIBRARY_REFRESH_START',
  LIBRARY_REFRESH_END = 'LIBRARY_REFRESH_END',
  LIBRARY_REFRESH_PROGRESS = 'LIBRARY_REFRESH_PROGRESS',
  LIBRARY_ADD_TRACKS = 'LIBRARY_ADD_TRACKS',
  LIBRARY_REMOVE_TRACKS = 'LIBRARY_REMOVE_TRACKS',
  LIBRARY_HIGHLIGHT_PLAYING_TRACK = 'LIBRARY_HIGHLIGHT_PLAYING_TRACK',
}

export default ActionTypes;
