enum ActionTypes {
  APP_LIBRARY_REFRESH = 'APP_LIBRARY_REFRESH',
  APP_REFRESH_CONFIG = 'APP_REFRESH_CONFIG',

  APP_FILTER_SEARCH = 'APP_FILTER_SEARCH',

  APP_PLAYER_START = 'APP_PLAYER_START',
  APP_PLAYER_TOGGLE = 'APP_PLAYER_TOGGLE',
  APP_PLAYER_PLAY = 'APP_PLAYER_PLAY',
  APP_PLAYER_PAUSE = 'APP_PLAYER_PAUSE',
  APP_PLAYER_STOP = 'APP_PLAYER_STOP',
  APP_PLAYER_NEXT = 'APP_PLAYER_NEXT',
  APP_PLAYER_PREVIOUS = 'APP_PLAYER_PREVIOUS',
  APP_PLAYER_JUMP_TO = 'APP_PLAYER_JUMP_TO',

  APP_PLAYER_SHUFFLE = 'APP_PLAYER_SHUFFLE',
  APP_PLAYER_REPEAT = 'APP_PLAYER_REPEAT',

  APP_QUEUE_START = 'APP_QUEUE_START',
  APP_QUEUE_CLEAR = 'APP_QUEUE_CLEAR',
  APP_QUEUE_REMOVE = 'APP_QUEUE_REMOVE',
  APP_QUEUE_ADD = 'APP_QUEUE_ADD',
  APP_QUEUE_ADD_NEXT = 'APP_QUEUE_ADD_NEXT',
  APP_QUEUE_SET_QUEUE = 'APP_QUEUE_SET_QUEUE',

  APP_LIBRARY_SORT = 'APP_LIBRARY_SORT',
  APP_LIBRARY_RESET = 'APP_LIBRARY_RESET',
  APP_LIBRARY_REFRESH_START = 'APP_LIBRARY_REFRESH_START',
  APP_LIBRARY_REFRESH_END = 'APP_LIBRARY_REFRESH_END',
  APP_LIBRARY_REFRESH_PROGRESS = 'APP_LIBRARY_REFRESH_PROGRESS',
  APP_LIBRARY_REMOVE_TRACKS = 'APP_LIBRARY_REMOVE_TRACKS',

  APP_PLAYLISTS_REFRESH = 'APP_PLAYLISTS_REFRESH',
  APP_PLAYLISTS_LOAD_ONE = 'APP_PLAYLISTS_LOAD_ONE',

  APP_TOAST_ADD = 'APP_TOAST_ADD',
  APP_TOAST_REMOVE = 'APP_TOAST_REMOVE',

  APP_NOTIFICATION_NEW = 'APP_NOTIFICATION_NEW'
}

export default ActionTypes;
